RENAME "ASPNET-Monsters-93-React.vtt" "ASP.NET Monsters #93 React.vtt"
RENAME "ASPNET-Monsters-92-Saving-CPU-Cycles-with-Static-Resource-Hashes.vtt" "ASP.NET Monsters #92 Saving CPU Cycles with Static Resource Hashes.vtt"
RENAME "ASPNET-Monsters-91-Middleware-vs-Filters.vtt" "ASP.NET Monsters #91 Middleware vs. Filters.vtt"
RENAME "ASPNET-Monsters-90-Formatting-Dates.vtt" "ASP.NET Monsters #90 Formatting Dates.vtt"
RENAME "ASPNET-Monsters-89-URL-Rewrite-Middleware.vtt" "ASP.NET Monsters #89 URL Rewrite Middleware.vtt"
RENAME "ASPNET-Monsters-88-Inside-Compiled-Views-in-the-Razor-View-Engine.vtt" "ASP.NET Monsters #88 Inside Compiled Views in the Razor View Engine.vtt"
RENAME "ASPNET-Monsters-87-Building-a-Roslyn-Analyser.vtt" "ASP.NET Monsters #87 Building a Roslyn Analyser.vtt"
RENAME "ASPNET-Monsters-86-Pugzor.vtt" "ASP.NET Monsters #86 Pugzor.vtt"
RENAME "ASPNET-Monsters-85-Suave-Web-Services.vtt" "ASP.NET Monsters #85 Suave Web Services.vtt"
RENAME "ASPNET-Monsters-84-Integration-Testing-with-Entity-Framework-Core.vtt" "ASP.NET Monsters #84 Integration Testing with Entity Framework Core.vtt"
RENAME "ASPNET-Monsters-83-A-Book-on-ASPNET-Core.vtt" "ASP.NET Monsters #83 A Book on ASP.NET Core.vtt"
RENAME "ASPNET-Monsters-82-Node-Services.vtt" "ASP.NET Monsters #82 Node Services.vtt"
RENAME "ASPNET-Monsters-81-Invoking-View-Components-as-Tag-Helpers.vtt" "ASP.NET Monsters #81 Invoking View Components as Tag Helpers.vtt"
RENAME "ASPNET-Monsters-80-ASPNET-11-was-ReleasedTime-to-Pump-the-Brakes.vtt" "ASP.NET Monsters #80 ASP.NET 1.1 was Released...Time to Pump the Brakes.vtt"
RENAME "ASPNET-Monsters-79-Code-Labs-with-Jon-Galloway.vtt" "ASP.NET Monsters #79 Code Labs with Jon Galloway.vtt"
RENAME "ASPNET-Monsters-78-Azure-Functions-with-Chris-Anderson.vtt" "ASP.NET Monsters #78 Azure Functions with Chris Anderson.vtt"
RENAME "ASPNET-Monsters-77-Internationalization-Part-2-Request-Localization.vtt" "ASP.NET Monsters #77 Internationalization Part 2 - Request Localization.vtt"
RENAME "ASPNET-Monsters-Episode-76-Curl.vtt" "ASP.NET Monsters #76 Curl.vtt"
RENAME "ASPNET-Monsters-75-Internationalization-Part-1-Localizing-Text.vtt" "ASP.NET Monsters #75 Internationalization Part 1 - Localizing Text.vtt"
RENAME "ASPNET-Monsters-74-Customizing-Bootstrap-4-in-Your-ASPNET-Core-MVC-Application.vtt" "ASP.NET Monsters #74 Customizing Bootstrap 4 in Your ASP.NET Core MVC Application.vtt"
RENAME "ASPNET-Monsters-73-Why-Do-I-Need-To-Know-What-a-Reverse-Proxy-Is.vtt" "ASP.NET Monsters #73 Why Do I Need To Know What a Reverse Proxy Is.vtt"
RENAME "ASPNET-Monsters-72-NET-Standard.vtt" "ASP.NET Monsters #72 .NET Standard.vtt"
RENAME "ASPNET-Monsters-71-Unit-Testing-with-xUnit.vtt" "ASP.NET Monsters #71 Unit Testing with xUnit.vtt"
RENAME "ASPNET-Monsters-70-Accessing-View-Context-from-Tag-Helpers.vtt" "ASP.NET Monsters #70 Accessing View Context from Tag Helpers.vtt"
RENAME "ASPNET-Monsters-69-Using-Scopes-To-Improve-Logging.vtt" "ASP.NET Monsters #69 Using Scopes To Improve Logging.vtt"
RENAME "ASPNET-Monsters-Ep-68-Creating-Custom-Conventions-for-ASPNET-Core-MVC.vtt" "ASP.NET Monsters #68 Creating Custom Conventions for ASP.NET Core MVC.vtt"
RENAME "ASPNET-Monsters-Ep-67-Gettting-JavaScript-to-the-Client.vtt" "ASP.NET Monsters #67 Gettting JavaScript to the Client.vtt"
RENAME "ASP-NET-Monsters-66-Content-Security-Policy-Headers.vtt" "ASP .NET Monsters #66 Content Security Policy Headers.vtt"
RENAME "ASPNET-Monsters-65-Programmatic-Authorization-with-IAuthorizationService.vtt" "ASP.NET Monsters #65 Programmatic Authorization with IAuthorizationService.vtt"
RENAME "ASPNET-Monsters-64-HTTPS-Strict-Transport-Security.vtt" "ASP.NET Monsters #64 HTTPS Strict Transport Security.vtt"
RENAME "ASPNET-Monsters-63-Model-Binding-in-ASPNET-Core.vtt" "ASP.NET Monsters #63 Model Binding in ASP.NET Core.vtt"
RENAME "ASPNET-Monsters-62-You-are-probably-using-HttpClient-wrong.vtt" "ASP.NET Monsters #62 You are probably using HttpClient wrong.vtt"
RENAME "ASPNET-Monsters-Summer-of-Config-Winners.vtt" "ASP.NET Monsters Summer of Config Winners.vtt"
RENAME "ASPNET-Monsters-61-Building-APIs-with-Darrel-Miller.vtt" "ASP.NET Monsters #61 Building APIs with Darrel Miller.vtt"
RENAME "ASPNET-Monsters-60-Projections-with-Entity-Framework-Core.vtt" "ASP.NET Monsters #60 Projections with Entity Framework Core.vtt"
RENAME "ASPNET-Monsters-59-Razor-with-Taylor-Mullen.vtt" "ASP.NET Monsters #59 The Razor View Engine with Taylor Mullen.vtt"
RENAME "ASPNET-Monsters-58-Nginx-Kestrel-and-SSL.vtt" "ASP.NET Monsters #58 Nginx, Kestrel and SSL.vtt"
RENAME "ASPNET-Monsters-Episode-57-Loading-Related-Data-with-Entity-Framework-Core.vtt" "ASP.NET Monsters #57 Loading Related Data with Entity Framework Core.vtt"
RENAME "ASP-NET-Monsters-Episode-56-Summer-of-Config-Prize-Update.vtt" "ASP .NET Monsters #56 Summer of Config Prize Update.vtt"
RENAME "ASPNET-Monsters-55-Jeffrey-Palermo-on-Moving-the-Business-to-ASPNET-Core.vtt" "ASP.NET Monsters #55 Jeffrey Palermo on Moving the Business to ASP.NET Core.vtt"
RENAME "ASP-NET-Monsters-Episode-54-Static-Compile.vtt" "ASP.NET Monsters #54 Static Compilation in ASP.NET Core.vtt"
RENAME "ASPNET-Monsters-53-Web-API-with-Guest-Eric-Fleming.vtt" "ASP.NET Monsters #53 Web API with Guest Eric Fleming.vtt"
RENAME "ASPNET-Monsters-Episode-52-Loading-View-Components-from-a-Class-Library.vtt" "ASP.NET Monsters #52 Loading View Components from a Class Library.vtt"
RENAME "ASPNET-Monsters-Episode-51-An-Intro-to-Nginx-for-Kestrel.vtt" "ASP.NET Monsters #51 An Intro to Nginx for Kestrel.vtt"
RENAME "Summer-of-Config.vtt" "Summer of Config Write ASP.NET Core Code and Get Loot.vtt"
RENAME "ASPNET-Monsters-Episode-50-Configuration-From-Any-Source-in-ASPNET-Core.vtt" "ASP.NET Monsters #50 Configuration From Any Source in ASP.NET Core.vtt"
RENAME "ASPNET-Monsters-Episode-49-Right-Click-Deployment.vtt" "ASP.NET Monsters #49 Right Click Deployment.vtt"
RENAME "ASPNET-Monsters-Episode-48-Configuring-Entity-Framework.vtt" "ASP.NET Monsters #48 Configuring Entity Framework.vtt"
RENAME "ASPNET-Monsters-Episode-47-Julie-Lerman-and-the-State-of-EF-Core.vtt" "ASP.NET Monsters #47 Julie Lerman and the State of EF Core.vtt"
RENAME "ASPNET-Monsters-Episode-46-Finding-Platform-Information.vtt" "ASP.NET Monsters #46 Finding Platform Information.vtt"
RENAME "ASPNET-Monsters-Episode-45-Generating-Complex-Realistic-Data-For-Tests-and-Prototypes.vtt" "ASP.NET Monsters #45 Generating Complex, Realistic Data For Tests and Prototypes.vtt"
RENAME "ASPNET-Monsters-Episode-44-Developing-with-NET-Core-on-Ubuntu-Desktop.vtt" "ASP.NET Monsters #44 Developing with .NET Core on Ubuntu Desktop.vtt"
RENAME "ASPNET-Monsters-Episode-43-Hello-Bundler-Minifier-with-Mads-Kristensen.vtt" "ASP.NET Monsters #43 Hello Bundler Minifier with Mads Kristensen.vtt"
RENAME "ASPNET-Monsters-Episode-42-Goodbye-to-Gulp.vtt" "ASP.NET Monsters #42 Goodbye to Gulp.vtt"
RENAME "ASPNET-Monsters-Episode-41-Accessing-SQL-Server.vtt" "ASP.NET Monsters #41 Accessing SQL Server.vtt"
RENAME "ASPNET-Monsters-40-Understanding-and-Enabling-CORS-in-ASPNET-Core.vtt" "ASP.NET Monsters #40 Understanding and Enabling CORS in ASP.NET Core.vtt"
RENAME "ASPNET-Monsters-39-Creating-Tokens-for-Basic-API-Authentication.vtt" "ASP.NET Monsters #39 Creating Tokens for Basic API Authentication.vtt"
RENAME "ASPNET-Monsters-Episode-38-Yeoman.vtt" "ASP.NET Monsters #38 Yeoman Reprised.vtt"
RENAME "ASPNET-Monsters-37-Compiling-a-Custom-Bootstrap-Template-with-Gulp.vtt" "ASP.NET Monsters #37 Compiling a Custom Bootstrap Template with Gulp.vtt"
RENAME "ASPNET-Monsters-36-Redis-Distributed-Cache-in-Core-MVC.vtt" "ASP.NET Monsters #36 Redis Distributed Cache in Core MVC.vtt"
RENAME "Episode-35-Distributed-Cache-Tag-Helper.vtt" "ASP.NET Monsters #35 Distributed Cache Tag Helper.vtt"
RENAME "Episode-34-Routing.vtt" "ASP.NET Monsters #34 Routing.vtt"
RENAME "EP33-RC2-is-here.vtt" "ASP.NET Monsters #33 RC2 is here!.vtt"
RENAME "Episode-32-In-Memory-Caching-with-ASPNET-Core.vtt" "ASP.NET Monsters #32 In-Memory Caching with ASP.NET Core.vtt"
RENAME "Episode-31-Migrating-to-Bootstrap-4.vtt" "ASP.NET Monsters #31 Migrating to Bootstrap 4.vtt"
RENAME "Episode-30-dotnet-on-OSX.vtt" "ASP.NET Monsters #30 dotnet on OSX.vtt"
RENAME "Episode-29-Working-with-Developer-Pages.vtt" "ASP.NET Monsters #29 Working with Developer Pages.vtt"
RENAME "Episode-28-Integrated-Payments-with-Stripe-in-ASPNET-Core-MVC.vtt" "ASP.NET Monsters #28 Integrated Payments with Stripe in ASP.NET Core MVC.vtt"
RENAME "Episode-27-Windows-Containers.vtt" "ASP.NET Monsters #27 Windows Docker Containers.vtt"
RENAME "Episode-26-GitHub-Authentication-in-ASPNET-Core.vtt" "ASP.NET Monsters #26 GitHub Authentication in ASP.NET Core.vtt"
RENAME "Episode-25-Dependency-Injection-into-Filters.vtt" "ASP.NET Monsters #25 Dependency Injection into Filters.vtt"
RENAME "Episode-24-View-Components-in-ASPNET-MVC-Core.vtt" "ASP.NET Monsters #24 View Components in ASP.NET MVC Core.vtt"
RENAME "Episode-23-Working-With-Sensitive-Data-User-Secrets.vtt" "ASP.NET Monsters #23 Working With Sensitive Data User Secrets.vtt"
RENAME "Episode-22-Realistic-Prototype-Data-in-ASPNET-Core-with-GenFu.vtt" "ASP.NET Monsters #22 Realistic Prototype Data in ASP.NET Core with GenFu.vtt"
RENAME "Episode-21-Caching.vtt" "ASP.NET Monsters #21 Donuts, Donut Holes & Razor Output Caching with Tag Helpers.vtt"
RENAME "Episode-20-Docs-and-GitHub-Repos.vtt" "ASP.NET Monsters #20 Docs and GitHub Repos.vtt"
RENAME "Episode-19-Building-Advanced-Tag-Helpers.vtt" "ASP.NET Monsters #19 Building Advanced Tag Helpers.vtt"
RENAME "Episode-18-Build-Hooks.vtt" "ASP.NET Monsters #18 Using Build Hooks to Build Docker Containers.vtt"
RENAME "Episode-17-Structured-Logging-with-Serilog-in-ASPNET-Core.vtt" "ASP.NET Monsters #17 Structured Logging with Serilog in ASP.NET Core.vtt"
RENAME "Episode-16-Logging-Basics-in-ASPNET-Core.vtt" "ASP.NET Monsters #16 Logging Basics in ASP.NET Core.vtt"
RENAME "Episode-15-ASPNET-Core-on-Docker.vtt" "ASP.NET Monsters #15 ASP.NET Core on Docker.vtt"
RENAME "Episode-14-Docker.vtt" "ASP.NET Monsters #14 Docker.vtt"
RENAME "Episode-13-Basics-of-NET-Core.vtt" "ASP.NET Monsters #13 Basics of .NET Core.vtt"
RENAME "Episode-12-Dependency-Injection-in-ASPNET-Core.vtt" "ASP.NET Monsters #12 - Dependency Injection in ASP.NET Core.vtt"
RENAME "Episode-11-Yeomon-Generators-for-ASPNET-Core-and-MVC.vtt" "ASP.NET Monsters #11 - Yeoman Generators for ASP.NET Core and MVC.vtt"
RENAME "Episode-10-Loading-Settings-From-a-Database-in-ASPNET-Core.vtt" "ASP.NET Monsters #10 Loading Settings From a Database in ASP.NET Core.vtt"
RENAME "Episode-9-What-Makes-a-Controller.vtt" "ASP.NET Monsters #9 What Makes a Controller.vtt"
RENAME "Episode-8-Tour-of-the-Default-ASPNET-MVC-Project.vtt" "ASP.NET Monsters #8 Tour of the Default ASP.NET MVC Project.vtt"
RENAME "Episode-7-Custom-Tag-Helpers.vtt" "ASP.NET Monsters #7 Custom Tag Helpers.vtt"
RENAME "Episode-6-JSON-Data-and-The-Options-Pattern.vtt" "ASP.NET Monsters #6 JSON Data and The Options Pattern.vtt"
RENAME "Episode-5-Configuration-Settings.vtt" "ASP.NET Monsters #5 Configuration Settings.vtt"
RENAME "Episode-4-Tag-Helpers-in-Razor.vtt" "ASP.NET Monsters #4 Tag Helpers in Razor.vtt"
RENAME "Episode-3-Default-Gulp-File.vtt" "Episode 3 - Default Gulp File.vtt"
RENAME "Episode-2-Static-Files.vtt" "ASP.NET Monsters #2 Static Files.vtt"
RENAME "Episode-1-Startupcs.vtt" "ASP.NET Monsters #1 Startup.cs.vtt"
