RENAME "react1_high.mp4" "ASP.NET Monsters #93 React.mp4"
RENAME "EP92_high.mp4" "ASP.NET Monsters #92 Saving CPU Cycles with Static Resource Hashes.mp4"
RENAME "ep91_mid.mp4" "ASP.NET Monsters #91 Middleware vs. Filters.mp4"
RENAME "EP90_high.mp4" "ASP.NET Monsters #90 Formatting Dates.mp4"
RENAME "EP89_high.mp4" "ASP.NET Monsters #89 URL Rewrite Middleware.mp4"
RENAME "ep88_mid.mp4" "ASP.NET Monsters #88 Inside Compiled Views in the Razor View Engine.mp4"
RENAME "roslyn_high.mp4" "ASP.NET Monsters #87 Building a Roslyn Analyser.mp4"
RENAME "EP86_high.mp4" "ASP.NET Monsters #86 Pugzor.mp4"
RENAME "suave_high.mp4" "ASP.NET Monsters #85 Suave Web Services.mp4"
RENAME "EP84_mid.mp4" "ASP.NET Monsters #84 Integration Testing with Entity Framework Core.mp4"
RENAME "EP83_mid.mp4" "ASP.NET Monsters #83 A Book on ASP.NET Core.mp4"
RENAME "nodeservices_high.mp4" "ASP.NET Monsters #82 Node Services.mp4"
RENAME "EP81_mid.mp4" "ASP.NET Monsters #81 Invoking View Components as Tag Helpers.mp4"
RENAME "ep80_mid.mp4" "ASP.NET Monsters #80 ASP.NET 1.1 was Released...Time to Pump the Brakes.mp4"
RENAME "EP79_mid.mp4" "ASP.NET Monsters #79 Code Labs with Jon Galloway.mp4"
RENAME "EP78_mid.mp4" "ASP.NET Monsters #78 Azure Functions with Chris Anderson.mp4"
RENAME "EP77_mid.mp4" "ASP.NET Monsters #77 Internationalization Part 2 - Request Localization.mp4"
RENAME "curl_high.mp4" "ASP.NET Monsters #76 Curl.mp4"
RENAME "EP75_mid.mp4" "ASP.NET Monsters #75 Internationalization Part 1 - Localizing Text.mp4"
RENAME "ep74_mid.mp4" "ASP.NET Monsters #74 Customizing Bootstrap 4 in Your ASP.NET Core MVC Application.mp4"
RENAME "ep73_mid.mp4" "ASP.NET Monsters #73 Why Do I Need To Know What a Reverse Proxy Is.mp4"
RENAME "netstandard.mp4" "ASP.NET Monsters #72 .NET Standard.mp4"
RENAME "EP71_mid.mp4" "ASP.NET Monsters #71 Unit Testing with xUnit.mp4"
RENAME "ep70_mid.mp4" "ASP.NET Monsters #70 Accessing View Context from Tag Helpers.mp4"
RENAME "ep69_mid.mp4" "ASP.NET Monsters #69 Using Scopes To Improve Logging.mp4"
RENAME "ep68_mid.mp4" "ASP.NET Monsters #68 Creating Custom Conventions for ASP.NET Core MVC.mp4"
RENAME "javascriptservertoclient_high.mp4" "ASP.NET Monsters #67 Gettting JavaScript to the Client.mp4"
RENAME "csp_high.mp4" "ASP .NET Monsters #66 Content Security Policy Headers.mp4"
RENAME "EP65_mid.mp4" "ASP.NET Monsters #65 Programmatic Authorization with IAuthorizationService.mp4"
RENAME "hsts_high.mp4" "ASP.NET Monsters #64 HTTPS Strict Transport Security.mp4"
RENAME "ep63_mid.mp4" "ASP.NET Monsters #63 Model Binding in ASP.NET Core.mp4"
RENAME "socket_high.mp4" "ASP.NET Monsters #62 You are probably using HttpClient wrong.mp4"
RENAME "socwinners_mid.mp4" "ASP.NET Monsters Summer of Config Winners.mp4"
RENAME "EP61_mid.mp4" "ASP.NET Monsters #61 Building APIs with Darrel Miller.mp4"
RENAME "EP60_mid.mp4" "ASP.NET Monsters #60 Projections with Entity Framework Core.mp4"
RENAME "EP59_mid.mp4" "ASP.NET Monsters #59 The Razor View Engine with Taylor Mullen.mp4"
RENAME "nginx2_high.mp4" "ASP.NET Monsters #58 Nginx, Kestrel and SSL.mp4"
RENAME "EP57_mid.mp4" "ASP.NET Monsters #57 Loading Related Data with Entity Framework Core.mp4"
RENAME "summerprizeupdate_high.mp4" "ASP .NET Monsters #56 Summer of Config Prize Update.mp4"
RENAME "ep55_mid.mp4" "ASP.NET Monsters #55 Jeffrey Palermo on Moving the Business to ASP.NET Core.mp4"
RENAME "staticcompile.mp4" "ASP.NET Monsters #54 Static Compilation in ASP.NET Core.mp4"
RENAME "ep53_mid.mp4" "ASP.NET Monsters #53 Web API with Guest Eric Fleming.mp4"
RENAME "ep52_mid.mp4" "ASP.NET Monsters #52 Loading View Components from a Class Library.mp4"
RENAME "kestrel_high.mp4" "ASP.NET Monsters #51 An Intro to Nginx for Kestrel.mp4"
RENAME "summerofconfig_mid.mp4" "Summer of Config Write ASP.NET Core Code and Get Loot.mp4"
RENAME "ep50_mid.mp4" "ASP.NET Monsters #50 Configuration From Any Source in ASP.NET Core.mp4"
RENAME "rightclick_high.mp4" "ASP.NET Monsters #49 Right Click Deployment.mp4"
RENAME "ep48_mid.mp4" "ASP.NET Monsters #48 Configuring Entity Framework.mp4"
RENAME "ep47_mid.mp4" "ASP.NET Monsters #47 Julie Lerman and the State of EF Core.mp4"
RENAME "multiplatform_high.mp4" "ASP.NET Monsters #46 Finding Platform Information.mp4"
RENAME "ep45_mid.mp4" "ASP.NET Monsters #45 Generating Complex, Realistic Data For Tests and Prototypes.mp4"
RENAME "ep44.mp4" "ASP.NET Monsters #44 Developing with .NET Core on Ubuntu Desktop.mp4"
RENAME "ep43_mid.mp4" "ASP.NET Monsters #43 Hello Bundler Minifier with Mads Kristensen.mp4"
RENAME "bundler_high.mp4" "ASP.NET Monsters #42 Goodbye to Gulp.mp4"
RENAME "sqlserver_high.mp4" "ASP.NET Monsters #41 Accessing SQL Server.mp4"
RENAME "ep401_mid.mp4" "ASP.NET Monsters #40 Understanding and Enabling CORS in ASP.NET Core.mp4"
RENAME "ep39_mid.mp4" "ASP.NET Monsters #39 Creating Tokens for Basic API Authentication.mp4"
RENAME "yeoman2_high.mp4" "ASP.NET Monsters #38 Yeoman Reprised.mp4"
RENAME "EP37_mid.mp4" "ASP.NET Monsters #37 Compiling a Custom Bootstrap Template with Gulp.mp4"
RENAME "ep35_mid.mp4" "ASP.NET Monsters #36 Redis Distributed Cache in Core MVC.mp4"
RENAME "EP35_mid.mp4" "ASP.NET Monsters #35 Distributed Cache Tag Helper.mp4"
RENAME "routing_high.mp4" "ASP.NET Monsters #34 Routing.mp4"
RENAME "EP33_mid.mp4" "ASP.NET Monsters #33 RC2 is here!.mp4"
RENAME "ep32_mid.mp4" "ASP.NET Monsters #32 In-Memory Caching with ASP.NET Core.mp4"
RENAME "EP31_mid.mp4" "ASP.NET Monsters #31 Migrating to Bootstrap 4.mp4"
RENAME "dotnet1_mid.mp4" "ASP.NET Monsters #30 dotnet on OSX.mp4"
RENAME "ep29_mid.mp4" "ASP.NET Monsters #29 Working with Developer Pages.mp4"
RENAME "ep28stripe_mid.mp4" "ASP.NET Monsters #28 Integrated Payments with Stripe in ASP.NET Core MVC.mp4"
RENAME "windowsdocker_high.mp4" "ASP.NET Monsters #27 Windows Docker Containers.mp4"
RENAME "ep26_mid.mp4" "ASP.NET Monsters #26 GitHub Authentication in ASP.NET Core.mp4"
RENAME "difilters_high.mp4" "ASP.NET Monsters #25 Dependency Injection into Filters.mp4"
RENAME "ep24_mid.mp4" "ASP.NET Monsters #24 View Components in ASP.NET MVC Core.mp4"
RENAME "ep23_mid.mp4" "ASP.NET Monsters #23 Working With Sensitive Data User Secrets.mp4"
RENAME "ep22_mid.mp4" "ASP.NET Monsters #22 Realistic Prototype Data in ASP.NET Core with GenFu.mp4"
RENAME "ep21_mid.mp4" "ASP.NET Monsters #21 Donuts, Donut Holes & Razor Output Caching with Tag Helpers.mp4"
RENAME "EP20_mid.mp4" "ASP.NET Monsters #20 Docs and GitHub Repos.mp4"
RENAME "Episode19BuildingAdvancedTagHelpers_mid.mp4" "ASP.NET Monsters #19 Building Advanced Tag Helpers.mp4"
RENAME "buildhooks_high.mp4" "ASP.NET Monsters #18 Using Build Hooks to Build Docker Containers.mp4"
RENAME "ep17sl_mid.mp4" "ASP.NET Monsters #17 Structured Logging with Serilog in ASP.NET Core.mp4"
RENAME "Episode16_mid.mp4" "ASP.NET Monsters #16 Logging Basics in ASP.NET Core.mp4"
RENAME "docker2_mid.mp4" "ASP.NET Monsters #15 ASP.NET Core on Docker.mp4"
RENAME "docker_high.mp4" "ASP.NET Monsters #14 Docker.mp4"
RENAME "MonstersEpisode13_mid.mp4" "ASP.NET Monsters #13 Basics of .NET Core.mp4"
RENAME "ep12_mid.mp4" "ASP.NET Monsters #12 - Dependency Injection in ASP.NET Core.mp4"
RENAME "ep11_mid.mp4" "ASP.NET Monsters #11 - Yeoman Generators for ASP.NET Core and MVC.mp4"
RENAME "ep10_mid.mp4" "ASP.NET Monsters #10 Loading Settings From a Database in ASP.NET Core.mp4"
RENAME "ep9monsters_mid.mp4" "ASP.NET Monsters #9 What Makes a Controller.mp4"
RENAME "Eppp8_mid.mp4" "ASP.NET Monsters #8 Tour of the Default ASP.NET MVC Project.mp4"
RENAME "ep77_mid.mp4" "ASP.NET Monsters #7 Custom Tag Helpers.mp4"
RENAME "JSONMonster_mid.mp4" "ASP.NET Monsters #6 JSON Data and The Options Pattern.mp4"
RENAME "Config_mid.mp4" "ASP.NET Monsters #5 Configuration Settings.mp4"
RENAME "Razor_mid.mp4" "ASP.NET Monsters #4 Tag Helpers in Razor.mp4"
RENAME "Gulp_mid.mp4" "Episode 3 - Default Gulp File.mp4"
RENAME "StaticFile_high.mp4" "ASP.NET Monsters #2 Static Files.mp4"
RENAME "Startupcs_high.mp4" "ASP.NET Monsters #1 Startup.cs.mp4"
