RENAME "Get-started-VSCode-Csharp-NET-Core-Windows.vtt" "Get started with VS Code using C# and .NET Core on Windows.vtt"
RENAME "Get-started-VSCode-NET-Core-Mac.vtt" "Get started with VS Code using C# and .NET Core on a Mac.vtt"
RENAME "Get-Started-NET-Core-Visual-Studio-2017.vtt" "Get Started with .NET Core and Visual Studio 2017.vtt"
RENAME "Get-Started-Visual-Studio-NET-Core.vtt" "Get Started with Visual Studio 2015 and .NET Core.vtt"
RENAME "Get-started-with-VS-Code-Csharp-dotnet-Core-Ubuntu.vtt" "Get started with VS Code using C# and .NET Core on Ubuntu.vtt"
RENAME "Get-started-with-VS-Code-using-CSharp-and-NET-Core-on-MacOS.vtt" "Get started with VS Code using C# and .NET Core on macOS.vtt"
RENAME "Get-started-with-VS-Code-using-CSharp-and-NET-Core.vtt" "Get started with VS Code using C# and .NET Core on Windows.vtt"
RENAME "NET-for-UWP-Part-4-Advanced-CoreFX-Topics.vtt" ".NET for UWP Part 4 Advanced CoreFX Topics.vtt"
RENAME "NET-for-UWP-Part-3-Advanced-NET-Native-Topics.vtt" "NET for UWP Part 3 Advanced .NET Native Topics.vtt"
RENAME "NET-for-UWP-Part-2-Introduction-to-NET-Native.vtt" ".NET for UWP Part 2 Introduction to .NET Native.vtt"
RENAME "NET-for-UWP-Part-1-Introduction-to-CoreFX.vtt" ".NET for UWP Part 1 Introduction to CoreFX.vtt"
RENAME "Explorer-Interns-Roslyn-Diagnostic-Analyzer-Tutorial.vtt" "Explorer Interns' Roslyn Diagnostic Analyzer Tutorial.vtt"
RENAME "First-NET-Port-Award.vtt" "First .NET Port Award in Portland at dotnetfringe.vtt"
RENAME "NET-Core-API-Review-2015-04-28.vtt" ".NET Core API Review 2015-04-28.vtt"
RENAME "NET-Internals-2015-03-11.vtt" ".NET Internals 2015-03-11 ASP.NET v5 and DNX.vtt"
RENAME "NET-Foundations-2015-03-04.vtt" ".NET Internals 2015-03-04 .NET Core & Cross Platform.vtt"
RENAME "NET-Foundations-2015-02-25.vtt" ".NET Internals 2015-02-25 Open Source.vtt"
RENAME "github-for-the-roslyn-team.vtt" "GitHub for the Roslyn Team.vtt"
RENAME "CoreCLR-is-now-open-source-on-GitHub.vtt" "CoreCLR is now open source on GitHub.vtt"
