Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-started-VSCode-Csharp-NET-Core-Windows/captions?f=webvtt&l=zh-cn" -OutFile "Get started with VS Code using C# and .NET Core on Windows.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-started-VSCode-NET-Core-Mac/captions?f=webvtt&l=zh-cn" -OutFile "Get started with VS Code using C# and .NET Core on a Mac.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-Started-NET-Core-Visual-Studio-2017/captions?f=webvtt&l=zh-cn" -OutFile "Get Started with .NET Core and Visual Studio 2017.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-Started-Visual-Studio-NET-Core/captions?f=webvtt&l=zh-cn" -OutFile "Get Started with Visual Studio 2015 and .NET Core.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-Csharp-dotnet-Core-Ubuntu/captions?f=webvtt&l=zh-cn" -OutFile "Get started with VS Code using C# and .NET Core on Ubuntu.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core-on-MacOS/captions?f=webvtt&l=zh-cn" -OutFile "Get started with VS Code using C# and .NET Core on macOS.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core/captions?f=webvtt&l=zh-cn" -OutFile "Get started with VS Code using C# and .NET Core on Windows.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-for-UWP-Part-4-Advanced-CoreFX-Topics/captions?f=webvtt&l=zh-cn" -OutFile ".NET for UWP Part 4 Advanced CoreFX Topics.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-for-UWP-Part-3-Advanced-NET-Native-Topics/captions?f=webvtt&l=zh-cn" -OutFile "NET for UWP Part 3 Advanced .NET Native Topics.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-for-UWP-Part-2-Introduction-to-NET-Native/captions?f=webvtt&l=zh-cn" -OutFile ".NET for UWP Part 2 Introduction to .NET Native.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-for-UWP-Part-1-Introduction-to-CoreFX/captions?f=webvtt&l=zh-cn" -OutFile ".NET for UWP Part 1 Introduction to CoreFX.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/Explorer-Interns-Roslyn-Diagnostic-Analyzer-Tutorial/captions?f=webvtt&l=zh-cn" -OutFile "Explorer Interns' Roslyn Diagnostic Analyzer Tutorial.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/First-NET-Port-Award/captions?f=webvtt&l=zh-cn" -OutFile "First .NET Port Award in Portland at dotnetfringe.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-Core-API-Review-2015-04-28/captions?f=webvtt&l=zh-cn" -OutFile ".NET Core API Review 2015-04-28.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-Internals-2015-03-11/captions?f=webvtt&l=zh-cn" -OutFile ".NET Internals 2015-03-11 ASP.NET v5 and DNX.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-Foundations-2015-03-04/captions?f=webvtt&l=zh-cn" -OutFile ".NET Internals 2015-03-04 .NET Core & Cross Platform.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/NET-Foundations-2015-02-25/captions?f=webvtt&l=zh-cn" -OutFile ".NET Internals 2015-02-25 Open Source.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/github-for-the-roslyn-team/captions?f=webvtt&l=zh-cn" -OutFile "GitHub for the Roslyn Team.vtt"
Invoke-WebRequest "https://channel9.msdn.com/Blogs/dotnet/CoreCLR-is-now-open-source-on-GitHub/captions?f=webvtt&l=zh-cn" -OutFile "CoreCLR is now open source on GitHub.vtt"
