RENAME "NETCoreRefreshWindows.mp4" "Get started with VS Code using C# and .NET Core on Windows.mp4"
RENAME "NETCoreVSCodeWindows.mp4" "Get started with VS Code using C# and .NET Core on a Mac.mp4"
RENAME "NETCoreVS2017.mp4" "Get Started with .NET Core and Visual Studio 2017.mp4"
RENAME "VSCoreTutorial.mp4" "Get Started with Visual Studio 2015 and .NET Core.mp4"
RENAME "VSCodeLinuxTutorial.mp4" "Get started with VS Code using C# and .NET Core on Ubuntu.mp4"
RENAME "VSCodeMac.mp4" "Get started with VS Code using C# and .NET Core on macOS.mp4"
RENAME "VSCodeTutorialWindows.mp4" "Get started with VS Code using C# and .NET Core on Windows.mp4"
RENAME "dotnetuwppart4.mp4" ".NET for UWP Part 4 Advanced CoreFX Topics.mp4"
RENAME "dotnetuwppart3.mp4" "NET for UWP Part 3 Advanced .NET Native Topics.mp4"
RENAME "dotnetuwppart2.mp4" ".NET for UWP Part 2 Introduction to .NET Native.mp4"
RENAME "dotnetuwppart1.mp4" ".NET for UWP Part 1 Introduction to CoreFX.mp4"
RENAME "ExplorerRoslynScreencast.mp4" "Explorer Interns' Roslyn Diagnostic Analyzer Tutorial.mp4"
RENAME "firstdotnetportaward.mp4" "First .NET Port Award in Portland at dotnetfringe.mp4"
RENAME "APIReview20150428.mp4" ".NET Core API Review 2015-04-28.mp4"
RENAME "DotNetFoundations20150311.mp4" ".NET Internals 2015-03-11 ASP.NET v5 and DNX.mp4"
RENAME "DotNetFoundation20150304.mp4" ".NET Internals 2015-03-04 .NET Core & Cross Platform.mp4"
RENAME "DotNetFoundations20150225.mp4" ".NET Internals 2015-02-25 Open Source.mp4"
RENAME "RoslynGitHub.mp4" "GitHub for the Roslyn Team.mp4"
RENAME "CoreCLRonGitHub.mp4" "CoreCLR is now open source on GitHub.mp4"
