RENAME "NETCoreRefreshWindows_high.mp4" "Get started with VS Code using C# and .NET Core on Windows.mp4"
RENAME "NETCoreVSCodeWindows_high.mp4" "Get started with VS Code using C# and .NET Core on a Mac.mp4"
RENAME "NETCoreVS2017_high.mp4" "Get Started with .NET Core and Visual Studio 2017.mp4"
RENAME "VSCoreTutorial_high.mp4" "Get Started with Visual Studio 2015 and .NET Core.mp4"
RENAME "VSCodeLinuxTutorial_high.mp4" "Get started with VS Code using C# and .NET Core on Ubuntu.mp4"
RENAME "VSCodeMac_high.mp4" "Get started with VS Code using C# and .NET Core on macOS.mp4"
RENAME "VSCodeTutorialWindows_high.mp4" "Get started with VS Code using C# and .NET Core on Windows.mp4"
RENAME "dotnetuwppart4_high.mp4" ".NET for UWP Part 4 Advanced CoreFX Topics.mp4"
RENAME "dotnetuwppart3_high.mp4" "NET for UWP Part 3 Advanced .NET Native Topics.mp4"
RENAME "dotnetuwppart2_high.mp4" ".NET for UWP Part 2 Introduction to .NET Native.mp4"
RENAME "dotnetuwppart1_high.mp4" ".NET for UWP Part 1 Introduction to CoreFX.mp4"
RENAME "ExplorerRoslynScreencast_high.mp4" "Explorer Interns' Roslyn Diagnostic Analyzer Tutorial.mp4"
RENAME "firstdotnetportaward_high.mp4" "First .NET Port Award in Portland at dotnetfringe.mp4"
RENAME "APIReview20150428_mid.mp4" ".NET Core API Review 2015-04-28.mp4"
RENAME "DotNetFoundations20150311_mid.mp4" ".NET Internals 2015-03-11 ASP.NET v5 and DNX.mp4"
RENAME "DotNetFoundation20150304_mid.mp4" ".NET Internals 2015-03-04 .NET Core & Cross Platform.mp4"
RENAME "DotNetFoundations20150225.webm" ".NET Internals 2015-02-25 Open Source.webm"
RENAME "RoslynGitHub.webm" "GitHub for the Roslyn Team.webm"
RENAME "CoreCLRonGitHub.mp3" "CoreCLR is now open source on GitHub.mp3"
